### PR TITLE
Update 02_Technical_Starter_code.ipynb

### PR DESCRIPTION
**Pull request by DavidAKZ**
Hi,
I have been following the code in the book and have had to make amendments to run it. In this chapter, I have had to import matplotlib as plt in preference to np.histogram and add plt.show() to get the code to run.  I'm  a bit confused about using the object 'subplots' on p21 of the book as it is an object of class matplotlab and not np.histogram (?)

### CODE REVIEW

**Comment by mfenner1** [comment]
Hi @DavidAKZ .  Thanks for the question.  What comment in the book are you referencing?  I use matpotlib very widely throughout the book, so if I said otherwise ... the text needs to be fixed.  --Thanks, Mark

**Comment by DavidAKZ** [comment]
@mfenner1 . Thanks for your reply. I discovered  it was me that made the mistake. Basically confusing _**'matplotlib as plt'**_ with _**'numpy as np'**_. 

I would like to add one comment about generating the  Figure shown on p22.  For both methods of calculation, I had to add the following code to get the Figure to generate.

    import matplotlib.pyplot as plt
     plt.show()

Are you able to say in the following line what the meaning of '[0]' is 

    few_counts = np.histogram(few_rolls, bins=np.arange(0.5, 7.5))[0]

Regards, David

**Comment by mfenner1** [comment]
@DavidAKZ  

No worries!  The worst thing about code is that it does exactly (and only!) what we say.  For your questions:

(1) With plt.show(), that usually happens when you are running python from an interactive command line (or something like an IDE ... for example Spyder ...) and you have to force matplotlib to display stuff onscreen.  With current (recently updated jupyter notebooks), figures will display by default.  If you have an older notebook version, you may need to do %matplotlib inline. If you do that (in a jupyter notebook), you should see the figures displayed immediately below the cell with code that defines them.

(2)  `np.histogram` returns a few results.  We only need the first.  So, we select it with `[0]`.  You can see the full details with either `help(np.histogram)` or here:  https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

Best,
Mark

**Comment by DavidAKZ** [comment]
Thanks very much.

**Pull request closed without merging**
